import type { Component } from 'svelte';
import {
	Activity, Archive, ArrowDown, ArrowLeft, ArrowRight, ArrowUp,
	BadgeCheck, Ban, BarChart3, Bell, BellDot, BellRing, BookOpen, Bookmark, BookmarkPlus, Building, Building2,
	Calendar, Camera, Check, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Circle, CircleAlert, CircleCheck, CircleCheckBig, CircleHelp, CirclePlay, CirclePlus, ClipboardCheck, Clock, CloudDownload, CloudUpload, Code, Compass, Construction, Contact, Copy,
	Database, Download,
	ExternalLink,
	FilePen, FileText, FilterX, Flame,
	Gavel, GitBranch, GripVertical,
	Hand, Handshake, HardHat,
	Image, ImagePlus, Images, Info,
	Languages, Layers, LayoutDashboard, Lightbulb, ListChecks, ListFilter, ListTree, Loader2, LogIn, LogOut, Lock, LockOpen,
	Map, MapPin, Menu, Merge, Minus, MoreVertical,
	PanelRight, Pencil, PhoneForwarded, Play, Plus,
	Radar, Rocket,
	Search, SearchX, Shield, ShieldCheck, SlidersHorizontal, Smartphone, Snowflake, Sparkles, Square, SquareCheck, SquareMinus,
	Tag, Table, Thermometer, ThumbsUp, Timer, Trash, Trash2, TrendingUp, TriangleAlert, Trophy, Truck,
	UserPlus, Users,
	Wand2, Workflow,
	X,
} from 'lucide-svelte';

export const ICON_MAP: Record<string, Component> = {
	ac_unit: Snowflake,
	account_tree: ListTree,
	add: Plus,
	add_circle: CirclePlus,
	api: Code,
	apartment: Building,
	archive: Archive,
	bar_chart: BarChart3,
	arrow_back: ArrowLeft,
	arrow_downward: ArrowDown,
	arrow_forward: ArrowRight,
	arrow_upward: ArrowUp,
	auto_awesome: Sparkles,
	auto_fix_high: Wand2,
	block: Ban,
	bookmark: Bookmark,
	bookmark_add: BookmarkPlus,
	bookmarks: Bookmark,
	business: Building2,
	calendar_today: Calendar,
	camera: Camera,
	check: Check,
	check_box_outline_blank: Square,
	check_circle: CircleCheck,
	checklist: ListChecks,
	chevron_left: ChevronLeft,
	chevron_right: ChevronRight,
	circle: Circle,
	close: X,
	cloud_download: CloudDownload,
	cloud_upload: CloudUpload,
	construction: Construction,
	contacts: Contact,
	content_copy: Copy,
	conversion_path: Workflow,
	dashboard: LayoutDashboard,
	database: Database,
	delete: Trash2,
	delete_forever: Trash,
	description: FileText,
	deselect: SquareMinus,
	dock_to_right: PanelRight,
	domain_add: Building2,
	download: Download,
	drag_indicator: GripVertical,
	edit: Pencil,
	edit_note: FilePen,
	emoji_events: Trophy,
	engineering: HardHat,
	error: CircleAlert,
	expand_less: ChevronUp,
	expand_more: ChevronDown,
	explore: Compass,
	fact_check: ClipboardCheck,
	filter_alt_off: FilterX,
	filter_list: ListFilter,
	gavel: Gavel,
	handshake: Handshake,
	help_outline: CircleHelp,
	image: Image,
	image_plus: ImagePlus,
	images: Images,
	info: Info,
	language: Languages,
	languages: Languages,
	layers: Layers,
	lightbulb: Lightbulb,
	local_fire_department: Flame,
	local_shipping: Truck,
	location_on: MapPin,
	pin_drop: MapPin,
	progress_activity: Loader2,
	lock: Lock,
	lock_open: LockOpen,
	login: LogIn,
	logout: LogOut,
	map: Map,
	menu: Menu,
	menu_book: BookOpen,
	merge: Merge,
	monitoring: Activity,
	more_vert: MoreVertical,
	notification_important: BellDot,
	notifications: Bell,
	notifications_active: BellRing,
	open_in_new: ExternalLink,
	people: Users,
	person_add: UserPlus,
	phone_forwarded: PhoneForwarded,
	play_arrow: Play,
	play_circle: CirclePlay,
	radar: Radar,
	remove: Minus,
	rocket_launch: Rocket,
	schedule: Clock,
	search: Search,
	search_off: SearchX,
	security: ShieldCheck,
	select_all: SquareCheck,
	sell: Tag,
	shield: Shield,
	smartphone: Smartphone,
	source: GitBranch,
	stop: Square,
	table_chart: Table,
	task_alt: CircleCheckBig,
	thermostat: Thermometer,
	thumb_up: ThumbsUp,
	timer: Timer,
	trending_up: TrendingUp,
	tune: SlidersHorizontal,
	verified: BadgeCheck,
	warning: TriangleAlert,
	waving_hand: Hand,
};

export const FALLBACK_ICON: Component = CircleHelp;
