// Note : ICON_MAP typé avec `any` pour absorber le mismatch types
// Lucide-Svelte (legacy Svelte 4) vs Svelte 5 Component<>.
import {
	Activity, Archive, ArchiveRestore, ArrowDown, ArrowLeft, ArrowRight, ArrowUp,
	BadgeCheck, Ban, BarChart3, Bell, BellDot, BellRing, BookOpen, Bookmark, BookmarkPlus, Building, Building2,
	Calendar, Camera, Check, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Circle, CircleAlert, CircleCheck, CircleCheckBig, CircleHelp, CirclePlay, CirclePlus, ClipboardCheck, Clock, CloudDownload, CloudUpload, Code, Compass, Construction, Contact, Copy,
	Database, Download,
	Eye, EyeOff, ExternalLink,
	FilePen, FileText, FilterX, Flame,
	Gavel, GitBranch, GripVertical,
	Hand, Handshake, HardHat,
	Image, ImagePlus, Images, Info,
	Landmark, Languages, Layers, LayoutDashboard, LayoutGrid, Lightbulb, ListChecks, ListFilter, ListTree, Loader2, LogIn, LogOut, Lock, LockOpen,
	Mail, Map, MapPin, MapPinOff, Menu, Merge, Minus, MoreVertical, Navigation,
	PanelRight, Pencil, Phone, PhoneForwarded, Play, Plus,
	Radar, Repeat, Rocket, RotateCw,
	Search, SearchX, Shield, ShieldCheck, SlidersHorizontal, Smartphone, Snowflake, Sparkles, Square, SquareCheck, SquareMinus, StickyNote,
	Tag, Table, Table2, Target, Thermometer, ThumbsUp, Timer, Trash, Trash2, TrendingDown, TrendingUp, TriangleAlert, Trophy, Truck,
	ReceiptText, Coins,
	UserPlus, Users,
	Wand2, Workflow,
	X,
	Zap,
} from 'lucide-svelte';

// eslint-disable-next-line @typescript-eslint/no-explicit-any -- les composants lucide-svelte
// n'exposent pas de type commun stable ; `any` garde la table de mapping lisible (audit 360 V3b L-20).
export const ICON_MAP: Record<string, any> = {
	ac_unit: Snowflake,
	account_tree: ListTree,
	add: Plus,
	add_circle: CirclePlus,
	directions: Navigation,
	retry: RotateCw,
	api: Code,
	apartment: Building,
	archive: Archive,
	bar_chart: BarChart3,
	payments: Coins,
	receipt_long: ReceiptText,
	trending_down: TrendingDown,
	trending_flat: Minus,
	arrow_back: ArrowLeft,
	arrow_downward: ArrowDown,
	arrow_forward: ArrowRight,
	arrow_upward: ArrowUp,
	auto_awesome: Sparkles,
	auto_fix_high: Wand2,
	block: Ban,
	bolt: Zap,
	bookmark: Bookmark,
	bookmark_add: BookmarkPlus,
	bookmarks: Bookmark,
	business: Building2,
	call: Phone,
	calendar_today: Calendar,
	camera: Camera,
	check: Check,
	check_box_outline_blank: Square,
	check_circle: CircleCheck,
	checklist: ListChecks,
	chevron_left: ChevronLeft,
	chevron_right: ChevronRight,
	circle: Circle,
	close: X,
	cloud_download: CloudDownload,
	cloud_upload: CloudUpload,
	construction: Construction,
	contacts: Contact,
	content_copy: Copy,
	conversion_path: Workflow,
	dashboard: LayoutDashboard,
	database: Database,
	delete: Trash2,
	delete_forever: Trash,
	description: FileText,
	deselect: SquareMinus,
	dock_to_right: PanelRight,
	domain_add: Building2,
	download: Download,
	drag_indicator: GripVertical,
	edit: Pencil,
	edit_note: FilePen,
	emoji_events: Trophy,
	engineering: HardHat,
	error: CircleAlert,
	expand_less: ChevronUp,
	expand_more: ChevronDown,
	explore: Compass,
	fact_check: ClipboardCheck,
	fiber_new: Sparkles,
	filter_alt_off: FilterX,
	filter_list: ListFilter,
	gavel: Gavel,
	groups: Users,
	handshake: Handshake,
	help_outline: CircleHelp,
	mail: Mail,
	image: Image,
	image_plus: ImagePlus,
	images: Images,
	info: Info,
	language: Languages,
	languages: Languages,
	layers: Layers,
	lightbulb: Lightbulb,
	local_fire_department: Flame,
	local_shipping: Truck,
	location_on: MapPin,
	location_off: MapPinOff,
	table_rows: Table2,
	grid_view: LayoutGrid,
	pin_drop: MapPin,
	progress_activity: Loader2,
	lock: Lock,
	lock_open: LockOpen,
	login: LogIn,
	logout: LogOut,
	map: Map,
	menu: Menu,
	menu_book: BookOpen,
	merge: Merge,
	monitoring: Activity,
	more_vert: MoreVertical,
	note: StickyNote,
	notification_important: BellDot,
	notifications: Bell,
	notifications_active: BellRing,
	open_in_new: ExternalLink,
	people: Users,
	person_add: UserPlus,
	phone_forwarded: PhoneForwarded,
	users: Users,
	landmark: Landmark,
	repeat: Repeat,
	flame: Flame,
	target: Target,
	track_changes: Target,
	eye: Eye,
	eye_off: EyeOff,
	circle_x: Ban,
	circle_check_big: CircleCheckBig,
	play_arrow: Play,
	play_circle: CirclePlay,
	radar: Radar,
	remove: Minus,
	rocket_launch: Rocket,
	schedule: Clock,
	search: Search,
	search_off: SearchX,
	security: ShieldCheck,
	select_all: SquareCheck,
	sell: Tag,
	group: Users,
	do_not_disturb: Ban,
	visibility: Eye,
	unarchive: ArchiveRestore,
	shield: Shield,
	smartphone: Smartphone,
	source: GitBranch,
	stop: Square,
	table_chart: Table,
	task_alt: CircleCheckBig,
	thermostat: Thermometer,
	thumb_up: ThumbsUp,
	timer: Timer,
	trending_up: TrendingUp,
	tune: SlidersHorizontal,
	verified: BadgeCheck,
	warning: TriangleAlert,
	waving_hand: Hand,
};

// eslint-disable-next-line @typescript-eslint/no-explicit-any -- même raison que ICON_MAP : type
// composant lucide non exposé ; `any` aligné sur la valeur du map (audit 360 V3b L-20).
export const FALLBACK_ICON: any = CircleHelp;
