/**
 * Orchestrateur de génération + stockage d'images fallback pour items Veille.
 *
 * Appelé par generate.ts après enrichItemsWithOgImages :
 *  - pour chaque item où image_url est null après filtrage og,
 *  - on infère un segment lib depuis title+summary,
 *  - on génère une image via fal.ai (si segment inféré OU segment Veille mappable),
 *  - on l'upload dans media_library (source='fal-ai'),
 *  - on grave l'URL publique dans item.generated_image_url.
 *
 * Si fal.ai échoue ou si FAL_KEY est absente, generated_image_url reste null
 * et l'UI tombe sur la cascade fallback media_library (picker top-N).
 */

import { generateImageViaFal, buildFalPromptFromItem } from './image-generator-fal';
import { inferSegmentFromText } from './segment-mapper';
import { uploadMedia, getServiceClient } from '../media-library';

const BUCKET = 'media-library';
const DOWNLOAD_TIMEOUT_MS = 30_000;

interface ItemForGeneration {
	rank: number;
	title: string;
	summary?: string;
	segment?: string | null;
	image_url: string | null;
}

export interface GenerationOutcome {
	rank: number;
	status: 'generated' | 'skipped_has_image' | 'skipped_no_key' | 'failed';
	publicUrl?: string;
	reason?: string;
}

async function downloadImageBuffer(url: string): Promise<Buffer | null> {
	const controller = new AbortController();
	const t = setTimeout(() => controller.abort(), DOWNLOAD_TIMEOUT_MS);
	try {
		const res = await fetch(url, { signal: controller.signal });
		if (!res.ok) return null;
		const arr = new Uint8Array(await res.arrayBuffer());
		return Buffer.from(arr);
	} catch {
		return null;
	} finally {
		clearTimeout(t);
	}
}

/**
 * Génère et stocke une image fal.ai pour 1 item.
 */
export async function generateAndStoreFallback(
	item: ItemForGeneration,
	apiKey: string,
	supabaseUrl: string
): Promise<GenerationOutcome> {
	if (item.image_url) {
		return { rank: item.rank, status: 'skipped_has_image' };
	}

	const inferredSegment = inferSegmentFromText(item.title, item.summary ?? '');
	const promptSegment = inferredSegment ?? null;
	const prompt = buildFalPromptFromItem({
		title: item.title,
		segment: promptSegment
	});

	const gen = await generateImageViaFal({ prompt, apiKey });
	if (!gen.ok || !gen.url) {
		return { rank: item.rank, status: 'failed', reason: gen.reason ?? 'fal returned no url' };
	}

	const buffer = await downloadImageBuffer(gen.url);
	if (!buffer) {
		return { rank: item.rank, status: 'failed', reason: `download failed (${gen.url})` };
	}

	const supabase = getServiceClient();
	const upload = await uploadMedia(supabase, {
		buffer,
		source: 'fal-ai',
		source_url: gen.url,
		credit: 'Generated by fal.ai (Recraft V3)',
		license: 'fal.ai output',
		description: item.title,
		tags: ['fal-ai', 'generated', inferredSegment ?? 'general'],
		segment: inferredSegment ?? undefined,
		notes: `Auto-généré pipeline cron Veille rank=${item.rank}`
	});

	if (upload.status === 'error' || !upload.storage_path) {
		return {
			rank: item.rank,
			status: 'failed',
			reason: `upload failed: ${upload.reason ?? 'unknown'}`
		};
	}

	// Audit qualité backend : ne grave generated_image_url que si l'image
	// passe le seuil minimum (cohérent avec loadFallbackPool qui filtre >=7).
	// L'image reste en lib (orpheline pour cet item) — réutilisable par d'autres
	// rapports mais pas servie pour l'item en cours.
	const auditResult = await auditUploadedImage(supabase, upload.id!);
	if (!auditResult.ok) {
		return {
			rank: item.rank,
			status: 'failed',
			reason: `audit rejected: ${auditResult.reason}`
		};
	}

	const publicUrl = `${supabaseUrl}/storage/v1/object/public/${BUCKET}/${upload.storage_path}`;
	return { rank: item.rank, status: 'generated', publicUrl };
}

/**
 * Audit backend post-upload : récupère le row media_library complet pour valider
 * quality_score et is_placeholder. Évite de servir une image médiocre ou marquée
 * placeholder par qualityScore() (ratio aberrant, taille suspecte, format dégradé).
 */
const MIN_QUALITY_SCORE_FAL = 7;

async function auditUploadedImage(
	supabase: ReturnType<typeof getServiceClient>,
	mediaId: string
): Promise<{ ok: boolean; reason?: string }> {
	const { data, error } = await supabase
		.from('media_library')
		.select('quality_score, is_placeholder, width, height')
		.eq('id', mediaId)
		.maybeSingle();
	if (error || !data) {
		return { ok: false, reason: `audit fetch failed: ${error?.message ?? 'no row'}` };
	}
	if (data.is_placeholder) {
		return { ok: false, reason: 'flagged is_placeholder' };
	}
	if ((data.quality_score ?? 0) < MIN_QUALITY_SCORE_FAL) {
		return {
			ok: false,
			reason: `quality_score ${data.quality_score} < ${MIN_QUALITY_SCORE_FAL}`
		};
	}
	// Sanity dim : Recraft V3 landscape_16_9 attendu ~1820×1024. Tolérance large.
	if ((data.width ?? 0) < 800 || (data.height ?? 0) < 400) {
		return { ok: false, reason: `dimensions trop faibles ${data.width}x${data.height}` };
	}
	return { ok: true };
}

/**
 * Pipeline batch : génère pour tous les items qui en ont besoin.
 * Concurrence limitée (default 2) pour éviter de saturer fal.ai et la bande passante.
 */
export async function generateFallbacksForItems<T extends ItemForGeneration>(
	items: T[],
	options: { apiKey?: string; supabaseUrl: string; concurrency?: number } = { supabaseUrl: '' }
): Promise<{ items: (T & { generated_image_url?: string | null })[]; outcomes: GenerationOutcome[] }> {
	if (!options.apiKey) {
		return {
			items: items.map((it) => ({ ...it, generated_image_url: null })),
			outcomes: items.map((it) => ({ rank: it.rank, status: 'skipped_no_key' as const }))
		};
	}

	const concurrency = options.concurrency ?? 2;
	const targets = items
		.map((item, idx) => ({ item, idx }))
		.filter(({ item }) => !item.image_url);

	const result = items.map((it) => ({ ...it, generated_image_url: null as string | null }));
	const outcomes: GenerationOutcome[] = [];
	let cursor = 0;

	async function worker() {
		while (cursor < targets.length) {
			const current = targets[cursor++];
			const outcome = await generateAndStoreFallback(
				current.item,
				options.apiKey!,
				options.supabaseUrl
			);
			outcomes.push(outcome);
			if (outcome.status === 'generated' && outcome.publicUrl) {
				result[current.idx] = {
					...result[current.idx],
					generated_image_url: outcome.publicUrl
				};
			}
		}
	}

	await Promise.all(
		Array.from({ length: Math.min(concurrency, Math.max(targets.length, 1)) }, () => worker())
	);

	// Items qui avaient déjà une image_url → noté comme skipped
	for (const it of items) {
		if (it.image_url && !outcomes.find((o) => o.rank === it.rank)) {
			outcomes.push({ rank: it.rank, status: 'skipped_has_image' });
		}
	}

	return { items: result, outcomes };
}
